---
title: "Bibliogrpahy"
author: "Tom Gobardhan"
date: "26/05/2021"
bibliography: lahti.bib
csl: ergo.csl
output: md_document
---

# Bibliography

```{r bibtex, echo = FALSE, results = "asis", message=FALSE}
mybib <- RefManageR::ReadBib("lahti.bib", check = FALSE)

cite <- function(key, bib = mybib) {
  # create a silent reference so RefManageR
  # knows we've used this entry
  RefManageR::NoCite(bib, key)
  # create the string we need in the Markdown document
  paste0("[^", key, "]")
}
get_doi <- function(paper) {
  if (is.null(paper$doi)) {
    ""
  } else{
    paste0(" , https://doi.org/", paper$doi)
  }
}
```


This is our first citation`r cite("Zhu2021")`.

```{r bibtex2, echo = FALSE, results = "asis", message=FALSE}
#RefManageR::PrintBibliography(mybib)

# See https://ropensci.org/blog/2020/05/07/rmd-citations/
apa_style <- tools::bibstyle("apa", sortKeys = function(refs) seq_along(refs),
    #fmtPrefix = function(paper) paste0("[^", attr(paper,"key"), "]:"),
    fmtPrefix = function(paper) paste0(""),    
    #fmtPrefix = "",    
    extraInfo = function(paper) paste0(paper$url, get_doi(paper)),    
    .init = TRUE)
RefManageR::PrintBibliography(mybib, .opts = list(bib.style = "apa", sorting = ""))
```

